<?php

namespace AppBundle\Repository\Property;

/**
 * AbstractPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
