<?php

namespace AppBundle\Repository\Property;

/**
 * FatnessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FatnessRepository extends \Doctrine\ORM\EntityRepository
{
}
