<?php

namespace AppBundle\Repository\Property;

/**
 * VolumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolumeRepository extends \Doctrine\ORM\EntityRepository
{
}
